### ISSUE TITLE
Add a line with our names to the server

### ISSUE THREAD

**Issue by yonikesel1** [yonikesel1/sushi-dashboard#1]
We want to add our names to the page.

**Comment by Lkeselbrener** [comment]
Ok
Sounds good

**Comment by lmilbaum** [comment]
Could you clarify what does it mean to add our names to the page? Which page?

**Comment by yonikesel1** [comment]
And we wanted to check if we manage to update the message the server is returning when we access the root endpoint.
So I updated the message to include "By Yoni and Laurence".
Also, I added another endpoint "/Pairs" which makes an API call to the sushi subgraph and returns the first pair we get back.

**Comment by lmilbaum** [comment]
> And we wanted to check if we manage to update the message the server is returning when we access the root endpoint. So I updated the message to include "By Yoni and Laurence". Also, I added another endpoint "/Pairs" which makes an API call to the sushi subgraph and returns the first pair we get back.

Then, please link the issue to the PR. Another thing, the issue description was short and vague.

**Comment by yonikesel1** [comment]
@lmilbaum I linked the issue to the PR.
Regarding the issue description, I agree. Will keep it more descriptive in the future.
